version: '3.4'

services:
    s_redis:
        container_name: c_redis
        image: redis
    s_rabbitmq:
        # Username:guest  Password:guest
        container_name: c_rabbitmq
        image: rabbitmq:3-management
    s_consul:
        container_name: c_consul
        image: consul
    mongodb:
        image: mongo:4.2
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:  
                limits:
                    memory: 1g
    s_graylog:
     # Username:admin  Password:admin
     container_name: c_graylog
     image: graylog/graylog:4.0
    s_postgres:
        container_name: c_postgres
        image: postgres
    s_pg-admin:
        # admin email=admin@email.com
        # admin password=admin
        container_name: c_pg-admin
        image: dpage/pgadmin4:latest