// <auto-generated />
using BasketServiceApi.DataAccess.PostgreSqlConnect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BasketServiceApi.Migrations
{
    [DbContext(typeof(BasketDbContext))]
    [Migration("20230517230200_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BasketServiceApi.Entity.Concrete.BasketItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BasketId")
                        .HasColumnType("text");

                    b.Property<decimal>("OldUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("BasketServiceApi.Entity.Concrete.CustomerBasket", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("CustomerBaskets");
                });

            modelBuilder.Entity("BasketServiceApi.Entity.Concrete.BasketItem", b =>
                {
                    b.HasOne("BasketServiceApi.Entity.Concrete.CustomerBasket", null)
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId");
                });

            modelBuilder.Entity("BasketServiceApi.Entity.Concrete.CustomerBasket", b =>
                {
                    b.Navigation("BasketItems");
                });
#pragma warning restore 612, 618
        }
    }
}
